"""add_pdf_progress_fields

Revision ID: 48848b8ee23a
Revises: 464e9c52c2aa
Create Date: 2026-07-24 20:47:11.232730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48848b8ee23a'
down_revision: Union[str, Sequence[str], None] = '464e9c52c2aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('papers', sa.Column('progress', sa.Integer(), nullable=False))
    op.add_column('papers', sa.Column('metadata_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'metadata_json')
    op.drop_column('papers', 'progress')
    op.drop_column('papers', 'status')
    # ### end Alembic commands ###
