"""add_indexes_and_soft_deletes

Revision ID: be76f051c3f9
Revises: 48848b8ee23a
Create Date: 2026-07-24 20:49:04.304387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be76f051c3f9'
down_revision: Union[str, Sequence[str], None] = '48848b8ee23a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('result_text', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_reports_id'), 'ai_reports', ['id'], unique=False)
    op.add_column('conversations', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('conversations', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('documents', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index('idx_document_workspace_is_deleted', 'documents', ['workspace_id', 'is_deleted'], unique=False)
    op.create_index('idx_chunk_paper_id', 'paper_chunks', ['paper_id'], unique=False)
    op.add_column('papers', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('papers', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index('idx_paper_workspace_is_deleted', 'papers', ['workspace_id', 'is_deleted'], unique=False)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('workspace_shares', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('workspaces', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('workspaces', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index('idx_workspace_is_deleted', 'workspaces', ['id', 'is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_workspace_is_deleted', table_name='workspaces')
    op.drop_column('workspaces', 'updated_at')
    op.drop_column('workspaces', 'is_deleted')
    op.drop_column('workspace_shares', 'updated_at')
    op.drop_column('users', 'updated_at')
    op.drop_index('idx_paper_workspace_is_deleted', table_name='papers')
    op.drop_column('papers', 'updated_at')
    op.drop_column('papers', 'is_deleted')
    op.drop_index('idx_chunk_paper_id', table_name='paper_chunks')
    op.drop_index('idx_document_workspace_is_deleted', table_name='documents')
    op.drop_column('documents', 'is_deleted')
    op.drop_column('conversations', 'updated_at')
    op.drop_column('conversations', 'is_deleted')
    op.drop_index(op.f('ix_ai_reports_id'), table_name='ai_reports')
    op.drop_table('ai_reports')
    # ### end Alembic commands ###
